/**
 * 内置 Skill 的 Marketplace 包定义
 *
 * 将 5 个内置 Skill 包装为 Marketplace 条目，
 * 作为 Marketplace 的初始内容展示。
 */

import type { MarketplacePackage } from "./types.js";

const JARVIS_AUTHOR = {
  name: "Jarvis Team",
  email: "jarvis@example.com",
  verified: true,
};

export const BUILTIN_PACKAGES: MarketplacePackage[] = [
  {
    name: "@jarvis/skill-content-scraper",
    displayName: "内容采集器",
    description: "多平台热点内容采集与分析，支持小红书、微博、知乎等",
    version: "1.0.0",
    author: JARVIS_AUTHOR,
    category: "content",
    tags: ["采集", "爬虫", "热点", "scraping"],
    keywords: ["trending", "scrape", "crawler"],
    license: "MIT",
    repository: "https://github.com/jarvis-agent/agent-core",
    source: { type: "npm", url: "https://www.npmjs.com/package/@jarvis/agent-core", npmPackage: "@jarvis/agent-core" },
    tools: [
      { name: "scrape-trending", description: "采集热点话题", parameterCount: 2 },
      { name: "scrape-xhs-notes", description: "采集小红书笔记", parameterCount: 2 },
      { name: "scrape-url", description: "抓取网页内容", parameterCount: 1 },
      { name: "analyze-content", description: "分析内容质量", parameterCount: 1 },
    ],
    skillMeta: {
      name: "content-scraper",
      version: "1.0.0",
      description: "多平台热点内容采集与分析",
      category: "content",
      tags: ["采集", "爬虫", "热点"],
      triggers: ["采集", "热点", "爬取", "trending"],
      permissions: ["network"],
    },
    rating: { average: 4.8, count: 156, distribution: { 1: 2, 2: 3, 3: 8, 4: 28, 5: 115 } },
    downloads: { total: 2340, weekly: 87, monthly: 356 },
    compatibility: { minVersion: "0.1.0" },
    status: "active",
    publishedAt: new Date("2025-12-01"),
    updatedAt: new Date("2026-01-15"),
  },
  {
    name: "@jarvis/skill-content-writer",
    displayName: "AI 内容写手",
    description: "AI 驱动的内容生成，支持文章、摘要、标题、配图",
    version: "1.0.0",
    author: JARVIS_AUTHOR,
    category: "content",
    tags: ["AI", "生成", "写作", "GPT"],
    keywords: ["generate", "write", "AI", "content"],
    license: "MIT",
    repository: "https://github.com/jarvis-agent/agent-core",
    source: { type: "npm", url: "https://www.npmjs.com/package/@jarvis/agent-core", npmPackage: "@jarvis/agent-core" },
    tools: [
      { name: "ai-generate-content", description: "AI 生成文章内容", parameterCount: 3 },
      { name: "ai-generate-image", description: "AI 生成配图", parameterCount: 2 },
      { name: "ai-summarize", description: "AI 内容摘要", parameterCount: 1 },
    ],
    skillMeta: {
      name: "content-writer",
      version: "1.0.0",
      description: "AI 驱动的内容生成",
      category: "content",
      tags: ["AI", "生成", "写作"],
      triggers: ["写", "生成", "创作", "写文章"],
      permissions: ["llm"],
    },
    rating: { average: 4.9, count: 203, distribution: { 1: 1, 2: 2, 3: 5, 4: 22, 5: 173 } },
    downloads: { total: 3120, weekly: 120, monthly: 480 },
    compatibility: { minVersion: "0.1.0" },
    status: "active",
    publishedAt: new Date("2025-12-01"),
    updatedAt: new Date("2026-01-20"),
  },
  {
    name: "@jarvis/skill-xhs-publisher",
    displayName: "小红书发布",
    description: "小红书笔记发布、搜索、登录状态检查",
    version: "1.0.0",
    author: JARVIS_AUTHOR,
    category: "publish",
    tags: ["小红书", "发布", "XHS", "社交媒体"],
    keywords: ["xiaohongshu", "publish", "social"],
    license: "MIT",
    repository: "https://github.com/jarvis-agent/agent-core",
    source: { type: "npm", url: "https://www.npmjs.com/package/@jarvis/agent-core", npmPackage: "@jarvis/agent-core" },
    tools: [
      { name: "xhs-publish", description: "发布小红书笔记", parameterCount: 4 },
      { name: "xhs-search", description: "搜索小红书", parameterCount: 2 },
      { name: "xhs-check-login", description: "检查登录状态", parameterCount: 0 },
    ],
    skillMeta: {
      name: "xhs-publisher",
      version: "1.0.0",
      description: "小红书笔记发布",
      category: "publish",
      tags: ["小红书", "发布"],
      triggers: ["小红书", "XHS", "红书"],
      permissions: ["network"],
    },
    rating: { average: 4.6, count: 89, distribution: { 1: 1, 2: 3, 3: 7, 4: 20, 5: 58 } },
    downloads: { total: 1850, weekly: 65, monthly: 280 },
    compatibility: { minVersion: "0.1.0" },
    status: "active",
    publishedAt: new Date("2025-12-01"),
    updatedAt: new Date("2026-01-10"),
  },
  {
    name: "@jarvis/skill-wechat-publisher",
    displayName: "公众号发布",
    description: "微信公众号文章格式化与发布",
    version: "1.0.0",
    author: JARVIS_AUTHOR,
    category: "publish",
    tags: ["公众号", "微信", "发布", "WeChat"],
    keywords: ["wechat", "publish", "mp"],
    license: "MIT",
    repository: "https://github.com/jarvis-agent/agent-core",
    source: { type: "npm", url: "https://www.npmjs.com/package/@jarvis/agent-core", npmPackage: "@jarvis/agent-core" },
    tools: [
      { name: "wechat-publish", description: "发布公众号文章", parameterCount: 3 },
      { name: "wechat-format", description: "格式化文章", parameterCount: 2 },
    ],
    skillMeta: {
      name: "wechat-publisher",
      version: "1.0.0",
      description: "公众号文章格式化与发布",
      category: "publish",
      tags: ["公众号", "微信"],
      triggers: ["公众号", "微信", "WeChat"],
      permissions: ["network"],
    },
    rating: { average: 4.5, count: 67, distribution: { 1: 1, 2: 2, 3: 6, 4: 18, 5: 40 } },
    downloads: { total: 1420, weekly: 48, monthly: 210 },
    compatibility: { minVersion: "0.1.0" },
    status: "active",
    publishedAt: new Date("2025-12-01"),
    updatedAt: new Date("2026-01-12"),
  },
  {
    name: "@jarvis/skill-multi-distributor",
    displayName: "多平台分发",
    description: "一键分发内容到多个平台，支持状态检查和图片上传",
    version: "1.0.0",
    author: JARVIS_AUTHOR,
    category: "workflow",
    tags: ["分发", "多平台", "自动化"],
    keywords: ["distribute", "multi-platform", "automation"],
    license: "MIT",
    repository: "https://github.com/jarvis-agent/agent-core",
    source: { type: "npm", url: "https://www.npmjs.com/package/@jarvis/agent-core", npmPackage: "@jarvis/agent-core" },
    tools: [
      { name: "multi-publish", description: "多平台发布", parameterCount: 3 },
      { name: "check-platform-status", description: "检查平台状态", parameterCount: 1 },
      { name: "trigger-workflow", description: "触发工作流", parameterCount: 2 },
      { name: "upload-image", description: "上传图片到图床", parameterCount: 1 },
    ],
    skillMeta: {
      name: "multi-distributor",
      version: "1.0.0",
      description: "多平台内容分发",
      category: "workflow",
      tags: ["分发", "多平台"],
      triggers: ["分发", "多平台", "全平台"],
      permissions: ["network"],
    },
    rating: { average: 4.7, count: 112, distribution: { 1: 1, 2: 2, 3: 6, 4: 25, 5: 78 } },
    downloads: { total: 2080, weekly: 76, monthly: 310 },
    compatibility: { minVersion: "0.1.0" },
    status: "active",
    publishedAt: new Date("2025-12-01"),
    updatedAt: new Date("2026-01-18"),
  },
];

/** 获取所有内置包 */
export function getBuiltinPackages(): MarketplacePackage[] {
  return BUILTIN_PACKAGES;
}
